In [1]:
#Import relevant libraries
import numpy as np
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import requests
from time import sleep
from random import randint
from datetime import datetime
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
#Create a dictionary to store scrape data in (features as keys)
dict_movies = {'genre_0': [],
'genre_1': [],
'genre_2': [],
'genre_3': [],
'country': [],
'language': [],
'filming_locs':  [],
'production_co':  [],
'runtime':  [],
'budget':  [],
'gross_usa':  [],
'release': [],
'director':  [],
'rating': [],
'star_0': [],
'star_1': [],
'star_2': [],
'star_3': [],
'writer_0': [],
'writer_1': [],
'writer_2': [],
'review_count': [],
'title': [],
'open_week': [],
'cumulative': []}

In [3]:
#Create a list of URLS to scrape
urls = ['https://www.imdb.com/title/tt2975590/?ref_=adv_li_i',
        'https://www.imdb.com/title/tt2404233/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2674426/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2119532/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1386697/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt4649466/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1485796/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt0974015/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1396484/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5814060/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3799232/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6533240/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6911608/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3606756/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5164214/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1365519/?ref_=adv_li_i',
        'https://www.imdb.com/title/tt2704998/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1677720/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3104988/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6966692/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5463162/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt4154756/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2709692/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt0816692/?ref_=fn_al_tt_1', 
        'https://www.imdb.com/title/tt3315342/',
        'https://www.imdb.com/title/tt1754316/',
        'https://www.imdb.com/title/tt7394816/', 
        'https://www.imdb.com/title/tt1950235/', 
        'https://www.imdb.com/title/tt0137523/']

In [4]:
#loop through urls and scrape relevant features
for url in urls:
    resp = requests.get(url)
    
#     Pause the loop
#     sleep(randint(8,15))

    #Error if  status codes is not 200
    if resp.status_code != 200:
        warn('Request: {}; Status code: {}'.format(request, response.status_code))
    
    soup = BeautifulSoup(resp.text, 'html.parser')
    
    #get genres
    genres = soup.find_all('div', class_ = 'see-more inline canwrap')[1].find_all('a')
    dict_movies['genre_0'].append(genres[0].text)
    try:
        dict_movies['genre_1'].append(genres[1].text)
    except:
        dict_movies['genre_1'].append("")
    try:
        dict_movies['genre_2'].append(genres[2].text)
    except:
        dict_movies['genre_2'].append("")
    try:
        dict_movies['genre_3'].append(genres[3].text)
    except:
        dict_movies['genre_3'].append("")
    
    #Get country, language, filming location, production co, budget info variables
    other_specs = soup.find_all('div', class_ = 'txt-block')
    for i in range(len(other_specs)):
        if other_specs[i].find('h4', class_ = 'inline') is None:
            continue
        elif 'Country' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['country'].append(other_specs[i].a.text)
        elif 'Language' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['language'].append(other_specs[i].a.text)
        elif 'Filming Locations' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['filming_locs'].append(other_specs[i].a.text)
        elif 'Production Co' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['production_co'].append(other_specs[i].a.text)
        elif 'Runtime' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['runtime'].append(other_specs[i].time.text)
        elif 'Budget' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['budget'].append(other_specs[i].text)
            except: 
                dict_movies['budget'].append("")
        elif 'Gross USA' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['gross_usa'].append(other_specs[i].text)
            except:
                dict_movies['gross_usa'].append("")
        elif 'Opening Weekend USA' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['open_week'].append(other_specs[i].text)
            except:
                dict_movies['open_week'].append("")
        elif 'Cumulative Worldwide Gross' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['cumulative'].append(other_specs[i].text)
            except:
                dict_movies['cumulative'].append("")

    #get release date
    dict_movies['release'].append(soup.find_all('div', class_ = 'subtext')[0].find_all('a', title = "See more release dates")[0].text)
    
    #Get director, writer and stars    
    movie_containers = soup.find_all('div', class_ = 'credit_summary_item')
    dict_movies['director'].append(movie_containers[0].a.text)
    writers = movie_containers[1].find_all('a')
    dict_movies['writer_0'].append(writers[0].text)
    try:
        dict_movies['writer_1'].append(writers[1].text)
    except:
        dict_movies['writer_1'].append("")     
    try:
        dict_movies['writer_2'].append(writers[2].text)
    except:
        dict_movies['writer_2'].append("")
    stars = movie_containers[2].find_all('a')
    dict_movies['star_0'].append(stars[0].text)
    dict_movies['star_1'].append(stars[1].text)
    dict_movies['star_2'].append(stars[2].text)
    try:
        dict_movies['star_3'].append(stars[3].text)
    except:
        dict_movies['star_3'].append("")
        
    #Get raitng, review count and the title of the movie
    dict_movies['rating'].append(soup.find_all('span',{'itemprop':'ratingValue'})[0].text)
    dict_movies['review_count'].append(soup.find_all('span',{'itemprop':'ratingCount'})[0].text)
    dict_movies['title'].append(soup.find_all('title')[0].text)

In [5]:
#Convert scraping result dictionary into pandas dataframe
import pandas as pd
movies = pd.DataFrame.from_dict(dict_movies, orient='index').transpose()
movies.head()

,genre_0,genre_1,genre_2,genre_3,country,language,filming_locs,production_co,runtime,budget,...,star_1,star_2,star_3,writer_0,writer_1,writer_2,review_count,title,open_week,cumulative
0,Action,Adventure,Sci-Fi,,USA,English,"Detroit, Michigan, USA",Warner Bros.,151 min,"\nBudget:$250,000,000\n (estimated)\n",...,Henry Cavill,Amy Adams,See full cast & crew,Chris Terrio,David S. Goyer,5 more credits,"590,717",Batman v Superman: Dawn of Justice (2016) - IMDb,"\nOpening Weekend USA: $166,007,347,\n27 March...","\nCumulative Worldwide Gross: $873,634,919 ..."
1,Action,Adventure,Fantasy,,USA,English,"Fox Studios, Moore Park, Sydney, New South Wal...",Pyramania,127 min,"\nBudget:$140,000,000\n (estimated)\n",...,Nikolaj Coster-Waldau,Gerard Butler,See full cast & crew,Matt Sazama,Burk Sharpless,,"98,096",Gods of Egypt (2016) - IMDb,"\nOpening Weekend USA: $14,123,903,\n28 Februa...","\nCumulative Worldwide Gross: $150,680,864 ..."
2,Drama,Romance,,,UK,English,"Pembroke Castle, Pembrokeshire, Wales, UK",Metro-Goldwyn-Mayer (MGM),106 min,"\nBudget:$20,000,000\n (estimated)\n",...,Sam Claflin,Janet McTeer,See full cast & crew,Jojo Moyes,Jojo Moyes,,"184,361",Me Before You (2016) - IMDb,"\nOpening Weekend USA: $18,723,269,\n5 June 2016","\nCumulative Worldwide Gross: $208,314,186 ..."
3,Biography,Drama,History,War,Australia,English,"Sydney, New South Wales, Australia",Cross Creek Pictures,139 min,"\nBudget:$40,000,000\n (estimated)\n",...,Sam Worthington,Luke Bracey,See full cast & crew,Robert Schenkkan,Andrew Knight,,"385,002",Hacksaw Ridge (2016) - IMDb,"\nOpening Weekend USA: $15,190,758,\n6 Novembe...","\nCumulative Worldwide Gross: $175,302,354 ..."
4,Action,Adventure,Fantasy,Sci-Fi,USA,English,"Toronto, Ontario, Canada",Atlas Entertainment,123 min,"\nBudget:$175,000,000\n (estimated)\n",...,Jared Leto,Margot Robbie,See full cast & crew,David Ayer,,,"554,857",Suicide Squad (2016) - IMDb,"\nOpening Weekend USA: $133,682,248,\n7 August...","\nCumulative Worldwide Gross: $746,846,894 ..."

In [6]:
num_cols = ['runtime', 'budget', 'gross_usa', 'rating', 'review_count', 'open_week', 'cumulative']
clean_data = movies.copy()


# removing all strings from numeric columns 
for col in num_cols:
    clean_data[col] = (clean_data[col].str.replace('\D+', '')).astype("float64")


# cleaning null/place holder values   
clean_data = clean_data.drop(['filming_locs'], axis = 1)
clean_data = clean_data.fillna(0)
clean_data.replace(to_replace = "See full cast & crew", value = "", inplace = True)
clean_data.replace(to_replace = "[0-9][0-9]* more credits*", value = "", inplace = True, regex=True)

# removing 'bad' string from title and date (still need to fix datetime)
clean_data['title'] = clean_data['title'].str[0:-14]
clean_data['release'] = clean_data['release'].str[:-7]

clean_data.head()

,genre_0,genre_1,genre_2,genre_3,country,language,production_co,runtime,budget,gross_usa,...,star_1,star_2,star_3,writer_0,writer_1,writer_2,review_count,title,open_week,cumulative
0,Action,Adventure,Sci-Fi,,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,...,Henry Cavill,Amy Adams,,Chris Terrio,David S. Goyer,,590717.0,Batman v Superman: Dawn of Justice,1.660073e+14,873634919.0
1,Action,Adventure,Fantasy,,USA,English,Pyramania,127.0,140000000.0,31153464.0,...,Nikolaj Coster-Waldau,Gerard Butler,,Matt Sazama,Burk Sharpless,,98096.0,Gods of Egypt,1.412390e+13,150680864.0
2,Drama,Romance,,,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,...,Sam Claflin,Janet McTeer,,Jojo Moyes,Jojo Moyes,,184361.0,Me Before You,1.872327e+12,208314186.0
3,Biography,Drama,History,War,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,...,Sam Worthington,Luke Bracey,,Robert Schenkkan,Andrew Knight,,385002.0,Hacksaw Ridge,1.519076e+12,175302354.0
4,Action,Adventure,Fantasy,Sci-Fi,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,...,Jared Leto,Margot Robbie,,David Ayer,,,554857.0,Suicide Squad,1.336822e+13,746846894.0

In [7]:
# encoding genre as dummie variables
prepped_data = pd.get_dummies(clean_data, prefix_sep='_', columns = ['genre_0', 'genre_1', 'genre_2', 'genre_3'], drop_first=True)

#retreives all rows with 'genre'
genre_ls_all = prepped_data.filter(like='genre_').columns.tolist()

# aggregates genre buckets into single bucket
genre_ls = []
for item in genre_ls_all:
    if item[9:] not in genre_ls:
        genre_ls.append(item[9:])
        
for col in genre_ls:
    prepped_data[col] = prepped_data.filter(like = col).sum(axis = 1)
    
prepped_data = prepped_data[prepped_data.columns.drop(list(prepped_data.filter(regex='genre')))]
prepped_data['Music'].replace(2, 1, inplace=True)
prepped_data.head()

,country,language,production_co,runtime,budget,gross_usa,release,director,rating,star_0,...,Family,Musical,Mystery,Romance,Fantasy,History,Sci-Fi,Thriller,Music,War
0,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,25 March 2016,Zack Snyder,65.0,Ben Affleck,...,0,0,0,0,0,0,1,0,0,0
1,USA,English,Pyramania,127.0,140000000.0,31153464.0,26 February 2016,Alex Proyas,54.0,Brenton Thwaites,...,0,0,0,0,1,0,0,0,0,0
2,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,3 June 2016,Thea Sharrock,74.0,Emilia Clarke,...,0,0,0,1,0,0,0,0,0,0
3,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,4 November 2016,Mel Gibson,81.0,Andrew Garfield,...,0,0,0,0,0,1,0,0,0,1
4,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,5 August 2016,David Ayer,60.0,Will Smith,...,0,0,0,0,1,0,1,0,0,0

In [8]:
#Export dataframe to csv
# movies.to_csv('movies_scraping.csv',sep=',', index = None)