In [2]:
#Import relevant libraries
import numpy as np
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import requests
from time import sleep
from random import randint
from datetime import datetime

In [3]:
#Create a dictionary to store scrape data in (features as keys)
dict_movies = {'genre_0': [],
'genre_1': [],
'genre_2': [],
'genre_3': [],
'country': [],
'language': [],
'filming_locs':  [],
'production_co':  [],
'runtime':  [],
'budget':  [],
'gross_usa':  [],
'release': [],
'director':  [],
'rating': [],
'star_0': [],
'star_1': [],
'star_2': [],
'star_3': [],
'writer_0': [],
'writer_1': [],
'writer_2': [],
'review_count': [],
'title': [],
'open_week': [],
'cumulative': []}

In [4]:
#Create a list of URLS to scrape
urls = ['https://www.imdb.com/title/tt2975590/?ref_=adv_li_i',
        'https://www.imdb.com/title/tt2404233/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2674426/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2119532/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1386697/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt4649466/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1485796/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt0974015/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1396484/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5814060/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3799232/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6533240/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6911608/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3606756/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5164214/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1365519/?ref_=adv_li_i',
        'https://www.imdb.com/title/tt2704998/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt1677720/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt3104988/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt6966692/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt5463162/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt4154756/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt2709692/?ref_=adv_li_i', 
        'https://www.imdb.com/title/tt0816692/?ref_=fn_al_tt_1', 
        'https://www.imdb.com/title/tt3315342/',
        'https://www.imdb.com/title/tt1754316/',
        'https://www.imdb.com/title/tt7394816/', 
        'https://www.imdb.com/title/tt1950235/', 
        'https://www.imdb.com/title/tt0137523/']

In [6]:
#loop through urls and scrape relevant features
for url in urls:
    resp = requests.get(url)
    
#     Pause the loop
    sleep(randint(8,15))

    #Error if  status codes is not 200
    if resp.status_code != 200:
        warn('Request: {}; Status code: {}'.format(request, response.status_code))
    
    soup = BeautifulSoup(resp.text, 'html.parser')
    
    #get genres
    genres = soup.find_all('div', class_ = 'see-more inline canwrap')[1].find_all('a')
    dict_movies['genre_0'].append(genres[0].text)
    try:
        dict_movies['genre_1'].append(genres[1].text)
    except:
        dict_movies['genre_1'].append("")
    try:
        dict_movies['genre_2'].append(genres[2].text)
    except:
        dict_movies['genre_2'].append("")
    try:
        dict_movies['genre_3'].append(genres[3].text)
    except:
        dict_movies['genre_3'].append("")
    
    #Get country, language, filming location, production co, budget info variables
    other_specs = soup.find_all('div', class_ = 'txt-block')
    for i in range(len(other_specs)):
        if other_specs[i].find('h4', class_ = 'inline') is None:
            continue
        elif 'Country' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['country'].append(other_specs[i].a.text)
        elif 'Language' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['language'].append(other_specs[i].a.text)
        elif 'Filming Locations' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['filming_locs'].append(other_specs[i].a.text)
        elif 'Production Co' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['production_co'].append(other_specs[i].a.text)
        elif 'Runtime' in other_specs[i].find('h4', class_ = 'inline').text:
            dict_movies['runtime'].append(other_specs[i].time.text)
        elif 'Budget' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['budget'].append(other_specs[i].text)
            except: 
                dict_movies['budget'].append("")
        elif 'Gross USA' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['gross_usa'].append(other_specs[i].text)
            except:
                dict_movies['gross_usa'].append("")
        elif 'Opening Weekend USA' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['open_week'].append(other_specs[i].text)
            except:
                dict_movies['open_week'].append("")
        elif 'Cumulative Worldwide Gross' in other_specs[i].find('h4', class_ = 'inline').text:
            try:
                dict_movies['cumulative'].append(other_specs[i].text)
            except:
                dict_movies['cumulative'].append("")

    #get release date
    dict_movies['release'].append(soup.find_all('div', class_ = 'subtext')[0].find_all('a', title = "See more release dates")[0].text)
    
    #Get director, writer and stars    
    movie_containers = soup.find_all('div', class_ = 'credit_summary_item')
    dict_movies['director'].append(movie_containers[0].a.text)
    writers = movie_containers[1].find_all('a')
    dict_movies['writer_0'].append(writers[0].text)
    try:
        dict_movies['writer_1'].append(writers[1].text)
    except:
        dict_movies['writer_1'].append("")     
    try:
        dict_movies['writer_2'].append(writers[2].text)
    except:
        dict_movies['writer_2'].append("")
    stars = movie_containers[2].find_all('a')
    dict_movies['star_0'].append(stars[0].text)
    dict_movies['star_1'].append(stars[1].text)
    dict_movies['star_2'].append(stars[2].text)
    try:
        dict_movies['star_3'].append(stars[3].text)
    except:
        dict_movies['star_3'].append("")
        
    #Get raitng, review count and the title of the movie
    dict_movies['rating'].append(soup.find_all('span',{'itemprop':'ratingValue'})[0].text)
    dict_movies['review_count'].append(soup.find_all('span',{'itemprop':'ratingCount'})[0].text)
    dict_movies['title'].append(soup.find_all('title')[0].text)

In [7]:
#Convert scraping result dictionary into pandas dataframe
import pandas as pd
movies = pd.DataFrame.from_dict(dict_movies, orient='index').transpose()
movies.head()

,genre_0,genre_1,genre_2,genre_3,country,language,filming_locs,production_co,runtime,budget,...,star_1,star_2,star_3,writer_0,writer_1,writer_2,review_count,title,open_week,cumulative
0,Action,Adventure,Sci-Fi,,USA,English,"Detroit, Michigan, USA",Warner Bros.,151 min,"\nBudget:$250,000,000\n (estimated)\n",...,Henry Cavill,Amy Adams,See full cast & crew,Chris Terrio,David S. Goyer,5 more credits,"590,997",Batman v Superman: Dawn of Justice (2016) - IMDb,"\nOpening Weekend USA: $166,007,347,\n27 March...","\nCumulative Worldwide Gross: $873,634,919 ..."
1,Action,Adventure,Fantasy,,USA,English,"Fox Studios, Moore Park, Sydney, New South Wal...",Pyramania,127 min,"\nBudget:$140,000,000\n (estimated)\n",...,Nikolaj Coster-Waldau,Gerard Butler,See full cast & crew,Matt Sazama,Burk Sharpless,,"98,177",Gods of Egypt (2016) - IMDb,"\nOpening Weekend USA: $14,123,903,\n28 Februa...","\nCumulative Worldwide Gross: $150,680,864 ..."
2,Drama,Romance,,,UK,English,"Pembroke Castle, Pembrokeshire, Wales, UK",Metro-Goldwyn-Mayer (MGM),106 min,"\nBudget:$20,000,000\n (estimated)\n",...,Sam Claflin,Janet McTeer,See full cast & crew,Jojo Moyes,Jojo Moyes,,"184,588",Me Before You (2016) - IMDb,"\nOpening Weekend USA: $18,723,269,\n5 June 2016","\nCumulative Worldwide Gross: $208,314,186 ..."
3,Biography,Drama,History,War,Australia,English,"Sydney, New South Wales, Australia",Cross Creek Pictures,139 min,"\nBudget:$40,000,000\n (estimated)\n",...,Sam Worthington,Luke Bracey,See full cast & crew,Robert Schenkkan,Andrew Knight,,"385,527",Hacksaw Ridge (2016) - IMDb,"\nOpening Weekend USA: $15,190,758,\n6 Novembe...","\nCumulative Worldwide Gross: $175,302,354 ..."
4,Action,Adventure,Fantasy,Sci-Fi,USA,English,"Toronto, Ontario, Canada",Atlas Entertainment,123 min,"\nBudget:$175,000,000\n (estimated)\n",...,Jared Leto,Margot Robbie,See full cast & crew,David Ayer,,,"555,225",Suicide Squad (2016) - IMDb,"\nOpening Weekend USA: $133,682,248,\n7 August...","\nCumulative Worldwide Gross: $746,846,894 ..."

In [60]:
def remove_bad_characters(df):
    num_cols = ['runtime', 'budget', 'gross_usa', 'rating', 'review_count', 'open_week', 'cumulative']
    output = df.copy()
    
    # removing all strings from numeric columns 
    for col in num_cols:
        output[col] = (output[col].str.replace('\D+', '')).astype("float64")
        
    # cleaning null/place holder values   
    output = output.drop(['filming_locs'], axis = 1)
    output = output.fillna(0)
    output.replace(to_replace = "See full cast & crew", value = "", inplace = True)
    output.replace(to_replace = "[0-9][0-9]* more credits*", value = "", inplace = True, regex=True)
    
    # removing 'bad' string from title and date (still need to fix datetime)
    output['title'] = output['title'].str[0:-14]
    output['release'] = output['release'].str[:-7]
    
    return output

In [63]:
df1 = remove_bad_characters(movies)
df1.head()

,genre_0,genre_1,genre_2,genre_3,country,language,production_co,runtime,budget,gross_usa,...,star_1,star_2,star_3,writer_0,writer_1,writer_2,review_count,title,open_week,cumulative
0,Action,Adventure,Sci-Fi,,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,...,Henry Cavill,Amy Adams,,Chris Terrio,David S. Goyer,,590997.0,Batman v Superman: Dawn of Justice,1.660073e+14,873634919.0
1,Action,Adventure,Fantasy,,USA,English,Pyramania,127.0,140000000.0,31153464.0,...,Nikolaj Coster-Waldau,Gerard Butler,,Matt Sazama,Burk Sharpless,,98177.0,Gods of Egypt,1.412390e+13,150680864.0
2,Drama,Romance,,,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,...,Sam Claflin,Janet McTeer,,Jojo Moyes,Jojo Moyes,,184588.0,Me Before You,1.872327e+12,208314186.0
3,Biography,Drama,History,War,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,...,Sam Worthington,Luke Bracey,,Robert Schenkkan,Andrew Knight,,385527.0,Hacksaw Ridge,1.519076e+12,175302354.0
4,Action,Adventure,Fantasy,Sci-Fi,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,...,Jared Leto,Margot Robbie,,David Ayer,,,555225.0,Suicide Squad,1.336822e+13,746846894.0

In [64]:
def encode_genre(df):
    # encoding genre as dummie variables
    output = pd.get_dummies(df, prefix_sep='_', columns = ['genre_0', 'genre_1', 'genre_2', 'genre_3'], drop_first=True)

    #retreives all rows with 'genre'
    genre_ls_all = output.filter(like='genre_').columns.tolist()

    # aggregates genre buckets into single bucket
    genre_ls = []
    for item in genre_ls_all:
        if item[9:] not in genre_ls:
            genre_ls.append(item[9:])

    for col in genre_ls:
        output[col] = output.filter(like = col).sum(axis = 1)

    output = output[output.columns.drop(list(output.filter(regex='genre')))]
    output['Music'].replace(2, 1, inplace=True)
    
    return output

In [69]:
df2 = encode_genre(df1)
df2.head()

,country,language,production_co,runtime,budget,gross_usa,release,director,rating,star_0,...,Family,Musical,Mystery,Romance,Fantasy,History,Sci-Fi,Thriller,Music,War
0,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,25 March 2016,Zack Snyder,65.0,Ben Affleck,...,0,0,0,0,0,0,1,0,0,0
1,USA,English,Pyramania,127.0,140000000.0,31153464.0,26 February 2016,Alex Proyas,54.0,Brenton Thwaites,...,0,0,0,0,1,0,0,0,0,0
2,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,3 June 2016,Thea Sharrock,74.0,Emilia Clarke,...,0,0,0,1,0,0,0,0,0,0
3,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,4 November 2016,Mel Gibson,81.0,Andrew Garfield,...,0,0,0,0,0,1,0,0,0,1
4,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,5 August 2016,David Ayer,60.0,Will Smith,...,0,0,0,0,1,0,1,0,0,0

In [71]:
def adjust_years(df):
    output = df.release.str.split(' ', expand = True)
    output.columns = ['release_day', 'release_month', 'release_year']
    result = pd.concat([output.drop(['release_day'], axis = 1), df.drop(['release'], axis = 1)], axis = 1)
    result['release_year'] = result.release_year.astype('int')
    
    return result

In [74]:
df3 = adjust_years(df2)
df3.head()

,release_month,release_year,country,language,production_co,runtime,budget,gross_usa,director,rating,...,Family,Musical,Mystery,Romance,Fantasy,History,Sci-Fi,Thriller,Music,War
0,March,2016,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,Zack Snyder,65.0,...,0,0,0,0,0,0,1,0,0,0
1,February,2016,USA,English,Pyramania,127.0,140000000.0,31153464.0,Alex Proyas,54.0,...,0,0,0,0,1,0,0,0,0,0
2,June,2016,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,Thea Sharrock,74.0,...,0,0,0,1,0,0,0,0,0,0
3,November,2016,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,Mel Gibson,81.0,...,0,0,0,0,0,1,0,0,0,1
4,August,2016,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,David Ayer,60.0,...,0,0,0,0,1,0,1,0,0,0

In [54]:
# drop all rows without budget data

df3 = result.loc[(result[['budget', 'gross_usa', 'open_week', 'cumulative']] != 0).any(axis = 1)]
df3

,release_month,release_year,country,language,production_co,runtime,budget,gross_usa,director,rating,...,Family,Musical,Mystery,Romance,Fantasy,History,Sci-Fi,Thriller,Music,War
0,March,2016,USA,English,Warner Bros.,151.0,250000000.0,330360194.0,Zack Snyder,65.0,...,0,0,0,0,0,0,1,0,0,0
1,February,2016,USA,English,Pyramania,127.0,140000000.0,31153464.0,Alex Proyas,54.0,...,0,0,0,0,1,0,0,0,0,0
2,June,2016,UK,English,Metro-Goldwyn-Mayer (MGM),106.0,20000000.0,56245075.0,Thea Sharrock,74.0,...,0,0,0,1,0,0,0,0,0,0
3,November,2016,Australia,English,Cross Creek Pictures,139.0,40000000.0,67209615.0,Mel Gibson,81.0,...,0,0,0,0,0,1,0,0,0,1
4,August,2016,USA,English,Atlas Entertainment,123.0,175000000.0,325100054.0,David Ayer,60.0,...,0,0,0,0,1,0,1,0,0,0
5,September,2017,UK,English,Twentieth Century Fox,141.0,104000000.0,100234838.0,Matthew Vaughn,68.0,...,0,0,0,0,0,0,0,0,0,0
6,December,2017,USA,English,Chernin Entertainment,105.0,84000000.0,174340174.0,Michael Gracey,76.0,...,0,1,0,0,0,0,0,0,1,0
7,November,2017,USA,English,Warner Bros.,120.0,300000000.0,229024295.0,Zack Snyder,64.0,...,0,0,0,0,1,0,1,0,0,0
8,September,2017,USA,English,New Line Cinema,135.0,35000000.0,327481748.0,Andy Muschietti,73.0,...,0,0,0,0,0,0,0,0,0,0
9,September,2018,USA,English,Atomic Monster,96.0,22000000.0,117450119.0,Corin Hardy,53.0,...,0,0,1,0,0,0,0,1,0,0
10,May,2018,UK,English,Komixx Entertainment,105.0,75000000.0,120634935.0,Vince Marcello,61.0,...,0,0,0,1,0,0,0,0,0,0
11,September,2019,Canada,English,Arcola Entertainment,98.0,200000000.0,608581744.0,David Raymond,58.0,...,0,0,1,0,0,0,0,0,0,0
12,July,2018,UK,English,Universal Pictures,114.0,70000000.0,140218711.0,Ol Parker,67.0,...,0,1,0,1,0,0,0,0,1,0
13,June,2018,USA,English,Walt Disney Pictures,118.0,94000000.0,58250803.0,Brad Bird,77.0,...,0,0,0,0,0,0,0,0,0,0
14,June,2018,USA,English,Warner Bros.,110.0,37000000.0,69179066.0,Gary Ross,62.0,...,0,0,0,0,0,0,0,1,0,0
15,March,2018,UK,English,Metro-Goldwyn-Mayer (MGM),119.0,175000000.0,137690172.0,Roar Uthaug,63.0,...,0,0,0,0,1,0,0,1,0,0
16,February,2018,USA,English,Access Entertainment,100.0,30000000.0,174532921.0,John Francis Daley,69.0,...,0,0,1,0,0,0,0,0,0,0
17,March,2018,USA,English,Warner Bros.,140.0,23000000.0,85080171.0,Steven Spielberg,75.0,...,0,0,0,0,0,0,1,0,0,0
18,August,2018,USA,English,Warner Bros.,120.0,110000000.0,324591735.0,Jon M. Chu,69.0,...,0,0,0,1,0,0,0,0,0,0
19,November,2018,USA,English,Participant,130.0,321000000.0,678815482.0,Peter Farrelly,82.0,...,0,0,0,0,0,0,0,0,1,0
20,May,2018,USA,English,Twentieth Century Fox,119.0,75000000.0,270620950.0,David Leitch,77.0,...,0,0,0,0,0,0,1,0,0,0
21,April,2018,USA,English,Marvel Studios,149.0,165000000.0,188020017.0,Anthony Russo,85.0,...,0,0,0,0,0,0,1,0,0,0
22,November,2018,France,English,Universal Pictures,85.0,97000000.0,226277068.0,Yarrow Cheney,63.0,...,1,0,0,0,1,0,0,0,0,0
23,November,2014,USA,English,Paramount Pictures,169.0,63000000.0,37030102.0,Christopher Nolan,86.0,...,0,0,0,0,0,0,1,0,0,0
24,March,2017,USA,English,Twentieth Century Fox,137.0,0.0,0.0,James Mangold,81.0,...,0,0,0,0,0,0,1,1,0,0

In [8]:
#Export dataframe to csv
# movies.to_csv('movies_scraping.csv',sep=',', index = None)